### ISSUE TITLE
Emisión Boleta Bco Supervielle. Generación incorrecta de dígito verificador

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#27]
Ejemplo para probar: 
ID Afiliado: 2182
Cuota 9/2015
Importe 1: 865,00 - Venc1: 15/10/2015
Importe 2: 873,65 - Venc2: 30/10/2015
Valor incorrecto calculado: 79029010915151015301015086500087365021822
Valor correcto:                    790290109151510153010150865000873650218202
Solución: La longitud de dígito verificador es de 2.
Ver documento Sprint4. Cuadro Diseño Cód. barra Bco Supervielle.

**Comment by adruvene** [comment]
Corregido en  produccion (server) y ambiente locar

**Comment by rsherrera** [comment]
Testing Cliente: 19/10/2015
Estado: Resuelto.
