### ISSUE TITLE
Pago Automático. Pagar Banelco. Error en especificación posición campo Importe Pagado

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#33]
En doc. de Sprint 5, cuadro "Interpretación Archivos de Pago/Banelco", el campo Importe se especificó de la siguiente manera: 
-Importe Pagado: Posición Inicial: 58. Posición final: 69, longitud 10+2. Formato 000000661552.

La especificación correcta es: 
-Importe Pagado: Posición Inicial: 58. Posición final: 68, longitud 9+2.   Formato 00000086500.

**Comment by adruvene** [comment]
solucionado en producción y ambiente local

**Comment by rsherrera** [comment]
Testing 19/10/2015
Estado: Resuelto
