### ISSUE TITLE
Pago Automático. Pagar Banco San Juan. No importa Archivos de Bco SJ

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#35]
Pasos:
1º Seleccionar Examinar.
2º Buscar y seleccionar archivo BSddmmaaaa.txt
3º Seleccionar Importar.
Resultado: Sistema no importa el archivo y muestra el mensaje: No se pudo encontrar el archivo 'c:\windows\system32\inetsrv\BS081015.txt'

**Comment by rsherrera** [comment]
EL sistema solo interpreta archivos que empiezan con "BJ" y no con "BS".
Solución: El sistema deberá también interpretar archivos que inician con "BS"

**Comment by adruvene** [comment]
Se modifico en ambiente local, cdo se publique se podrá cargar en producción archivos con nombre BS tambien (por ahora solo funcionan archivos con nombre BJ).
