### ISSUE TITLE
Boletas con Interes. Cálculo incorrecto

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#38]
Fecha Detección: 08/10/2015
Detectó: Cliente

**Comment by adruvene** [comment]
Se arreglo en BD de producción (Server). Cdo me deje acceder algún día pobre copiar los cambios y aplicarlos a mi BD local...

**Comment by adruvene** [comment]
accedi al server!!!!!! y pude arreglar ambiente local idem a produccion

**Comment by rsherrera** [comment]
Testing Cliente: 19/10/2015
Estado: Resuelto.
