### ISSUE TITLE
Reingreso Afiliado. Sistema no permite reingreso de afiliado. (Ej.:6960)

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#45]
Fecha Detección: 19/10/2015
Autor: Cliente
Detalle del error:
Al seleccionar todos los datos correctamente para finalizar el proceso de reingreso, cuando selecciona Aceptar, el sistema muestra el siguiente mensaje de error: "Column name or number of supplied values does not match table definition". El sistema finalmente no permite el reingreso.
Posible causa: Store Procedure desactualizado.

**Comment by adruvene** [comment]
Se modifico store agregando el campo nivel al insert en tbl cuota y se cambio lógica cdo se debe cambia de nivel 1 a 2(siempre que este en nivel 1(elegido de manera automatico y no manual) y supero 60 meses la fecha de titulo). Antes se hacia luego de insertar cuotas pero como ahora el nivel es necesario en la tabla cuotas si o si debe cambiar antes el nivel del afiliado siempre que cumpla con las condiciones mencionadas.
Importante: Genera cuotas de aquellos mes aporte que tengan seteado campo emisionmasiva en 1.

**Comment by rsherrera** [comment]
Testing 1: Afiliado Inactivo, nivel 1 s/ opcionar, con antiguedad de fecha titulo superior a 60. Sin cuotas impagas. Resultado: OK. Activó afiliado en nivel 2, creó cuotas en nivel 2 y según la fecha de reingreso (01/10/2015), las cuotas creadas fueron de 10/2015 y 11/2015, insertó registro en legajo.

**Comment by rsherrera** [comment]
Testing 2: Afiliado Inactivo, nivel 1 s/ opcionar, con antiguedad de fecha titulo superior a 60 (27/09/2015). 
Resultado:  Activó afiliado en nivel 2, creó cuotas en nivel 2 y según la fecha de reingreso (01/07/2015), las cuotas creadas fueron de 7/2015, 8/2015, 9/2015 10/2015 y 11/2015 todas en Nivel 2, insertó registro en legajo.
Entiendo que El cliente pide que el resultado correcto de cuotas creadas deberia ser: 7/2015, 8/2015 en nivel 1 y  9/2015 10/2015 y 11/2015  en nivel 2. De todos modos NO ha quedado asi especificado, por lo que quedaría en caso de q asi lo requiera el cliente como una mejora.

**Comment by rsherrera** [comment]
Testing realizado en BD local. Se ejecuto en BD Local SP enviado via mail el dia 20/10/2015
