### ISSUE TITLE
Boletas Individual sin vencer y Boletas de Generación Masiva. Muestra el punto separador de unida de mil en el Nº Afiliado.

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#46]
Fecha informado: 19/10/2015
Informó: Cliente

**Comment by adruvene** [comment]
Solo en el reporte de boleta c interés es donde no tenia especificado formato (por eso mostraba el punto). NO lo puedo verificar en mi ambiente porque mi id afiliado no supera los 2 digitos x lo tanto no me sale el punto.

**Comment by rsherrera** [comment]
Testing: 21/10/2015
Estado: Resuelto
