### ISSUE TITLE
Boletas Individual vencidas. Muestra Importe 2do Venc. en lugar del Importe 1er Venc.

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#47]
Fecha Informe: 19/10/2015
Autor: Cliente
Detalle: El error es que en el campo "Importe de Aporte Previsional" muestra el valor de la cuota del 2do venc. en lugar del valor del 1er Venc.

**Comment by adruvene** [comment]
Se reemplazo el importe2 por importe 1 en campo:  Importe  Aporte Previsional. (en produccion y ambiente local)

**Comment by rsherrera** [comment]
Testing: 21/10/2015
Estado: Resuelto
