### ISSUE TITLE
Eximir Cuotas adeudadas. Se muestra valor incorrecto de cuotas. Ej.: Afiliado 6960

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#48]
Fecha Informe: 19/10/2015
Informó: Cliente
Detalle:
El sistema muestra en la ventana Eximir Cuotas Adeudadas, las cuotas Julio y Agosto de 2015, con los valores que corresponden al nivel 1, osea $655. Sin embargo, en tabla Cuota, esas cuotas fueron creadas con el nivel 2,
Nota: Al imprimir Gastos Administrativos, el sistema muestra correctamente los valores de cada cuota, osea valores en el nivel 2.

**Comment by adruvene** [comment]
En mi ambiente local ya me aparece arreglado eso. Cdo se agrego nivel se cambio pero no se de que día es la publicación que esta. Tendrías que mandarme la BD que esta en producción para probarlo.

**Comment by adruvene** [comment]
Se probo con BD de producción en ambiente local y funciona correctamente. Es problema de actualización de versión-> Solución publicar nva versión.
Se envió mail con captura de pantalla Fecha:23/10/2015 a 9.33hs

**Comment by rsherrera** [comment]
OK. Debemos pensar cuando podría ser la nueva publicación.

**Comment by rsherrera** [comment]
Testing ambiente local
BD Produccion
Publicación version 27/10/2015.
Resultado: Resuelto
