### ISSUE TITLE
Sw_v:20151119. Plan de Pago. Eliminación.  No se muestran planes de pagos a eliminar

### ISSUE THREAD

**Issue by rsherrera** [rsherrera/project-caja#63]
Elegir af. con planes de pagos sin inicio. Acceder a la opción Eliminar. El sistema muestra pantalla de Eliminación sin listar el o los planes de pagos en condiciones de ser eliminados

**Comment by adruvene** [comment]
Rodri anoche vi el email pero estaba muy cansada asi que vere hoy que es lo
q pasa.

**Comment by rsherrera** [comment]
Realicé pruebas con dos afiliados diferentes y no pude volver a reproducir el error
